default_platform(:ios)

platform :ios do
  desc "Build + Deploy to TestFlight"
  lane :beta do
    setup_ci

    match(
      type: "appstore",
      readonly: false,
      git_url: ENV["MATCH_GIT_URL"],
      git_basic_authorization: ENV["MATCH_GIT_BASIC_AUTHORIZATION"],
      git_branch: ENV["MATCH_GIT_BRANCH"] || "master"
    )

    # ✅ Use o mapping EXATO que o match gerou (inclui sufixo numérico)
    mapping = Actions.lane_context[SharedValues::MATCH_PROVISIONING_PROFILE_MAPPING]

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M")
    )

    gym(
      scheme: "App",
      project: "./App.xcodeproj",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      destination: "generic/platform=iOS",
      export_options: {
        signingStyle: "manual",
        teamID: ENV["APP_STORE_CONNECT_TEAM_ID"],
        provisioningProfiles: mapping
      },
      xcargs: "DEVELOPMENT_TEAM=#{ENV['APP_STORE_CONNECT_TEAM_ID']} CODE_SIGN_STYLE=Manual"
    )

    pilot(
      skip_waiting_for_build_processing: true
    )
  end
end

